"""adição da coluna cpf em Autor

Revision ID: e786c1692e67
Revises: 61df6d32e1af
Create Date: 2025-06-06 14:52:40.628852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e786c1692e67'
down_revision: Union[str, None] = '61df6d32e1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autor', sa.Column('cpf', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'autor', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autor', type_='unique')
    op.drop_column('autor', 'cpf')
    # ### end Alembic commands ###
